### ISSUE TITLE
rake shards:test:purge purges development shards instead of test shards

### ISSUE THREAD

**Issue by raphaelnogueira** [hsgubert/rails-sharding#7]

**Comment by hsgubert** [comment]
Indeed there is a bug in this rake task. Usually the task `db:test:purge` should purge the test database regardless of the configured rails environment. Since we want `shards:test:purge` to behave similarly, it should affect the test shards regardless of the environment as well.

**Comment by hsgubert** [comment]
Apparently the pull request did not fix the issue, because the connection to the shard databases is opened before the Rails.env is set to 'test'

**Comment by hsgubert** [comment]
Now its fixed! Thanks @raphaelnogueira
